web:
    build: .
    links:
        - database
    volumes:
        - .:/app
        - /app/var/cache
    ports:
        - 8080:80

database:
    image: mysql
    ports:
        - 3307:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: api_platform
        MYSQL_USER: api_platform
        MYSQL_PASSWORD: api_platform
